changed key generation to make pem files
the-maldridge/xbps-mini-builder pull request #3
Opened 2018-12-05 19:05 UTC by bobertlo

I might be missing something, but I just could not get xbps-rindex to work with the files being generated from this script. I then read in the xbps manual and it was using PEM when generating keys, and when I added that it worked right away.

Again, I don't know if this is just a personal issue, but this is how I fixed it for myself.

2018-12-10 08:15 UTC, the-maldridge commented
I'm not quite sure how this would have happened, as I can't reproduce this issue.  Can you explain more what you mean as the problem?

2018-12-10 08:53 UTC, bobertlo commented
I ran the script and it would not sign packages or repositories with the key it had generated. I even copied both keys into ~/.ssh/id_rsa (and .pub), and looked into the xbps-rindex source and couldn't see why it was not accepting the key generated by the script.

I then looked into the documentation on how to generate keys to sign packages, and the PEM option was present and I made new keys and it worked. I am on an update void host.

2018-12-10 19:18 UTC, bobertlo commented
FYI I checked out the repository again on my laptop, and get the same error. Whenever rindex is called to sign a repo or package:
```Trying to sign packages in nonfree
Updating repodata in hostdir/binpkgs/nonfree
xbps-rindex: failed to read the RSA privkey
Signing packages in hostdir/binpkgs/nonfree
xbps-rindex: failed to read the RSA privkey
```

2018-12-11 02:17 UTC, the-maldridge requested changes
I confirmed that my keys are PEM format, so this change can go ahead after the issue raised in this review is handled.

2018-12-11 02:17 UTC, the-maldridge commented on xbps-mini-builder
> +if [ ! -f id_rsa.pem ] ; then
Changing this filename breaks backwards compatibility and will cause existing users to have their entire repos untrusted.  Please keep the same filename and only modify the options.

2018-12-11 03:16 UTC, bobertlo commented
Changed this.

2018-12-12 04:08 UTC, the-maldridge approved these changes

2018-12-12 04:08 UTC, merged