docs: adds quick start example via snooze
the-maldridge/xbps-mini-builder pull request #7
Opened 2020-09-06 08:23 UTC by waynevanson

Adds a quick start example using `snooze` and `runit`.

No hard feelings if you don't want to merge this.
I'll add it somewhere else because I feel it's useful, predominately for beginners.

2020-09-06 08:55 UTC, the-maldridge requested changes
Ultimately a lot of what you're wanting to add as documentation should probably just be summed up by packaging the mini-builder.  As it has a limited use case I have not pursued this path, but your quickstart as written misses several important points in running the builder securely.

2020-09-06 08:55 UTC, the-maldridge commented on README.md
> +echo "snooze -d* <directory>/xbps-mini-installer" > /etc/sv/<service_name>/run
This should have an exec, should run as a different user, and `-d*` as it is a default value for snooze.

2020-09-06 08:55 UTC, the-maldridge commented on README.md
> +echo "package_one\npackage_two" >> <directory>/packages.list
This should be a heredoc for clarity, or a direction to use $editor.

2020-09-06 08:55 UTC, the-maldridge commented on README.md
> +# Add the service to runit
There should be a log symlink to vlogger prior to enabling the service.

2020-09-07 08:26 UTC, waynevanson commented
@the-maldridge  Thank you for your feedback.

Packaging the mini builder sounds like a good idea. 

Once it's packaged, then I'll come back and edit this.

2020-09-26 01:48 UTC, closed without merging